typography_spectrum: 0.36228
color:
  brandColors:
    - '#16b1ea'
    - '#bfe2fe'
    - '#047ac2'
    - '#5bc9ed'
    - '#002a4b'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75377
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Dickson Leung
name: 'Live Well, Love Much, Laugh Lots.'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ' Live Well, Love Much, Laugh Lots.'
purpose: []
