name: iamdicksonleung
favicon: null
layout_spectrum: 0.75377
typography_spectrum: 0.36228
title: 'I Am Dickson Leung - Live Well, Love Much, Laugh Lots.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16b1ea'
    - '#bfe2fe'
    - '#047ac2'
    - '#5bc9ed'
    - '#002a4b'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
